package com.cas.utils;

public class Utils {

	public enum Menu 
	{ 
	    SOCIETY_DETAILS_M, MEMBERS_M, SHARES_M, SOCIETY_EMPLOYEE_DETAILS_M, PDS_EMPLOYEE_DETAILS_M, RETIREMENT_DETAILS_M, AUDIT_DETAILS_M,
	    BOARD_DETAILS_M, DEPUTATION_DETAILS_M, PETITION_DETAILS_M, BONUS_DETAILS_M, PROMOTION_DETAILS_M, STOCK_VERIFICATION_M,
	    INSPECTION_M;
	}
}
